version: '3.1'

services:
  mariadb:
    container_name: wpsite_db
    image: 'mariadb:latest'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './.mariadb:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
    networks:
      - wpdev

  myadmin:
    container_name: wpsite_phpmyadmin
    image: 'phpmyadmin:latest'
    restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      PMA_HOSTS: mariadb
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mariadb
    networks:
      - wpdev

  wpsite.test:
    container_name: wpsite_code
    image: 'wordpress:latest'
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WORDPRESS_DB_HOST: '${DB_HOST}'
      WORDPRESS_DB_USER: '${DB_USERNAME}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_DATABASE}'
      WORDPRESS_DEBUG: 'true'
      PHP_IDE_CONFIG: 'serverName=docker'
      XDEBUG_CONFIG: 'remote_host=host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './public:/var/www/html'
      - './plugin:/var/www/html/wp-content/plugins/CurtainCallWP'
      - './xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    depends_on:
      - mariadb
      - myadmin
    networks:
      - wpdev

networks:
  wpdev:
    driver: bridge

volumes:
  mariadb:
    driver: local
